### ISSUE TITLE
Typo on page??

### ISSUE THREAD

**Issue by moderndevice** [mrahman4/AlexaSamTemplate#12]
On this page 

https://github.com/mrahman4/AlexaSamTemplate/blob/master/instructions/2-lambda-function.md

6) Enter fact to search for the application repository named alexa-skills-kit-nodejs-factskill. Enter the full name into the search box if you need to narrow the search results.

Shouldn't this repository search really be for:
alexa-nodejs-dynamic-content   ??

**Comment by mrahman4** [comment]
Thanks for your feedback. Issue fixed now. Please try again
