### ISSUE TITLE
Database Creation Intruction Bug ??

### ISSUE THREAD

**Issue by moderndevice** [mrahman4/AlexaSamTemplate#13]
on this page:
https://github.com/mrahman4/AlexaSamTemplate/blob/master/instructions/2-lambda-function.md

I think that the databases need to be created BEFORE the lambda file?
It seems like the lambda file tries to create them itself but this fails?

All the question marks are because I'm a new Alexa skill builder and am kind of wandering around in the dark trying to get this thing deployed.

These are my errors in the cloud formation stack
"Encountered unsupported property PrimaryKey" seems to be the smoking gun ??

2018-11-27 | Status | Type | Logical ID | Status Reason
-- | -- | -- | -- | --
14:11:56 UTC-0500 ROLLBACK_COMPLETE AWS::CloudFormation::Stack aws-serverless-repository-Alexa-Nodejs-Dynamic-Content      Physical ID:arn:aws:cloudformation:us-east-1:938377593660:stack/aws-serverless-repository-Alexa-Nodejs-Dynamic-Content/462e8010-f278-11e8-b999-1297d6a5b478      14:11:54 UTC-0500 ROLLBACK_IN_PROGRESS AWS::CloudFormation::Stack aws-serverless-repository-Alexa-Nodejs-Dynamic-Content  The following resource(s) failed to create: [StoriesTable, StoryPartsTable]. . Rollback requested by user.    Physical ID:arn:aws:cloudformation:us-east-1:938377593660:stack/aws-serverless-repository-Alexa-Nodejs-Dynamic-Content/462e8010-f278-11e8-b999-1297d6a5b478      14:11:53 UTC-0500 CREATE_FAILED AWS::DynamoDB::Table StoriesTable  Encountered unsupported property PrimaryKey       14:11:52 UTC-0500 CREATE_FAILED AWS::DynamoDB::Table StoryPartsTable  Encountered unsupported property PrimaryKey |   | 14:11:56 UTC-0500 | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | aws-serverless-repository-Alexa-Nodejs-Dynamic-Content |   |   | Physical ID:arn:aws:cloudformation:us-east-1:938377593660:stack/aws-serverless-repository-Alexa-Nodejs-Dynamic-Content/462e8010-f278-11e8-b999-1297d6a5b478 |   | 14:11:54 UTC-0500 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | aws-serverless-repository-Alexa-Nodejs-Dynamic-Content | The following resource(s) failed to create: [StoriesTable, StoryPartsTable]. . Rollback requested by user. |   | Physical ID:arn:aws:cloudformation:us-east-1:938377593660:stack/aws-serverless-repository-Alexa-Nodejs-Dynamic-Content/462e8010-f278-11e8-b999-1297d6a5b478 |   | 14:11:53 UTC-0500 | CREATE_FAILED | AWS::DynamoDB::Table | StoriesTable | Encountered unsupported property PrimaryKey |   | 14:11:52 UTC-0500 | CREATE_FAILED | AWS::DynamoDB::Table | StoryPartsTable | Encountered unsupported property PrimaryKey
  | 14:11:56 UTC-0500 | ROLLBACK_COMPLETE | AWS::CloudFormation::Stack | aws-serverless-repository-Alexa-Nodejs-Dynamic-Content |  
  | Physical ID:arn:aws:cloudformation:us-east-1:938377593660:stack/aws-serverless-repository-Alexa-Nodejs-Dynamic-Content/462e8010-f278-11e8-b999-1297d6a5b478
  | 14:11:54 UTC-0500 | ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | aws-serverless-repository-Alexa-Nodejs-Dynamic-Content | The following resource(s) failed to create: [StoriesTable, StoryPartsTable]. . Rollback requested by user.
  | Physical ID:arn:aws:cloudformation:us-east-1:938377593660:stack/aws-serverless-repository-Alexa-Nodejs-Dynamic-Content/462e8010-f278-11e8-b999-1297d6a5b478
  | 14:11:53 UTC-0500 | CREATE_FAILED | AWS::DynamoDB::Table | StoriesTable | Encountered unsupported property PrimaryKey
  | 14:11:52 UTC-0500 | CREATE_FAILED | AWS::DynamoDB::Table | StoryPartsTable | Encountered unsupported property PrimaryKey

**Comment by mrahman4** [comment]
Thanks for your feedback. Issue fixed now. Please try again

**Comment by moderndevice** [comment]
Mohamad,

Thank you so much for writing back.

Can you please be a little more specific. Does the template create the databases, or do I create them manually as in the instructions?

You also might think about adding a line in the instructions about what to do if the Deploy process fails. From my understanding one has to go to Cloud Formation and delete the stack? Is it possible for the template to delete the stack if it fails? My reading wasn't so clear on that because I'm a complete beginner to this process.

Also if you could briefly describe your toolchain (Eclipse? - something else? or you just program in AWS editor?) that would help me out a lot getting going.

Thanks much,

Paul
