### ISSUE TITLE
Instructions still point to the wrong Template

### ISSUE THREAD

**Issue by moderndevice** [mrahman4/AlexaSamTemplate#14]
in instructions/2-lambda-function.md

" Enter alexa to search for the application repository named alexa-skills-kit-nodejs-factskill. Enter the full name into the search box if you need to narrow the search results."

Also you might think about deleting the Database section since the template now sets up the databases.

I did confirm that the databases now get configured correctly.

**Comment by mrahman4** [comment]
Lambda section & DB section is needed in case you want to create tables manually.

**Comment by mrahman4** [comment]
Skill name in instruction is correct now. Thanks for your support:)
