### ISSUE TITLE
Lambda now builds correctly but finally app does not respond

### ISSUE THREAD

**Issue by moderndevice** [mrahman4/AlexaSamTemplate#15]
I put in the Endpoint (arn) and rebuilt the voice command side, but no joy when testing. Amazon finds  LaunchRequest input  but then something goes wrong and a generic error message comes up "There was a problem  with the requested skill's response."

	"request": {
		"type": "LaunchRequest",
		"requestId": "amzn1.echo-api.request.810dbef4-731d-4412-8e95-b33ef3900c6a",
		"timestamp": "2018-11-29T03:21:57Z",
		"locale": "en-US",
		"shouldLinkResultBeReturned": false
	}

JSON output
null

Can you confirm that the voice command section builds with the lambda and works correctly?

Thanks much,

Paul

**Comment by moderndevice** [comment]
I pasted in the json input into the test console and got this 

Response:
{
  "errorMessage": "Cannot find module '/var/task/index'",
  "errorType": "Error",
  "stackTrace": []
}

Also when I open my lambda function - the editor asks me for an index.js file. Is this required or needed now? Maybe a version change thing?

**Comment by mrahman4** [comment]
You are totally correct. I just fix this error
