### ISSUE TITLE
Lambda file still fails to respond correctly "Cannot find module 'alexa-sdk'"

### ISSUE THREAD

**Issue by moderndevice** [mrahman4/AlexaSamTemplate#16]
Response:
{
  "errorMessage": "Cannot find module 'alexa-sdk'",
  "errorType": "Error",
  "stackTrace": [
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}

**Comment by mrahman4** [comment]
Ok i figured the issue and working on it now.

**Comment by mrahman4** [comment]
check now
