### ISSUE TITLE
Having loaded the database no Story seems to exist

### ISSUE THREAD

**Issue by jimshalo10** [mrahman4/AlexaSamTemplate#6]
Having manually added the database all the information, there is no example story

**Comment by mrahman4** [comment]
Yes Database is downloaded empty so every one add his stories.
Do you suggest to add sample story in DB? 
Or should i add a concrete example here in documentation?

**Comment by jimshalo10** [comment]
Initially code works better if there is an example story for people to look at. We developers focus so much on the code and functionality that we forget new developers need to start with a template example
I would add a concrete sample in the documentation which can be used to populate the database, this makes developers thinks about the setting up of the new story

**Comment by jimshalo10** [comment]
When a concrete sample in the documentation which can be used to populate the database, then spelling grammar can be checked and amended. Then maybe we can develop extra tools for making and testing individual new stories

**Comment by mrahman4** [comment]
I added a sample story with one part. Please check and tell me what you think

**Comment by jimshalo10** [comment]
Investigating Text Adventure sample [skill]( https://github.com/alexa/skill-sample-nodejs-adventure-game) there is example [stories](https://github.com/alexa/skill-sample-nodejs-adventure-game/blob/master/lambda/custom/Escape%20the%20Office.html) in  _./lambda/custom_  directory
The [skill]( https://github.com/alexa/skill-sample-nodejs-adventure-game) builds and works with the Alexa Echo, the testing function of the Alexa Development console and [ASK-Cli console](https://developer.amazon.com/docs/smapi/quick-start-alexa-skills-kit-command-line-interface.html) as described in the [skill]( https://github.com/alexa/skill-sample-nodejs-adventure-game)  [Readme.md](https://github.com/alexa/skill-sample-nodejs-adventure-game/blob/master/README.md)

**Comment by jimshalo10** [comment]
>           I added a sample story with one part. Please check and tell me what you think
The update looks great, the whole story is loaded, cannot see any spelling or grammar errors.
the  "largeImageUrl", posed a problem as we didn't have any graphic content of Miriam, so we do now its in the debugextras/"who is Miriam a 11 year old female warrior character create using Unreal Game Engine AI" has  a shortened name for coding use  debugextras/WhoAmIMiriam.jpg

**Comment by jimshalo10** [comment]
>           I added a sample story with one part. Please check and tell me what you think
More Requests received for Miriam's Bibliography so now a new file [MiriamREADME.md](https://github.com/jimshalo10/AlexaSamTemplate/blob/master/debugextras/MiriamREADME.md)  has been made about her lift. If you read you will see a subtle twist!
